### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by StepToTop** [noterpopo/Hands-Chopping#1]
为什么你的APP这么流畅，我上steam都会卡。

**Comment by noterpopo** [comment]
无可奉告
![avatar](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1530180636270&di=2c1ab89abd9a608632ea8276d5edfad8&imgtype=0&src=http%3A%2F%2Fimg1.55you.com%2FUpImages%2F2016-7%2F2016715115518141.jpg)
