### ISSUE TITLE
想问一下项目里面为什么没有用到ButterKnife注解呢

### ISSUE THREAD

**Issue by XiaoGe-1996** [noterpopo/Hands-Chopping#3]

**Comment by XiaoGe-1996** [comment]
如果需要使用的话  该怎么做呢，为什么我使用BindView（R.id.xbanner）会报错

**Comment by XiaoGe-1996** [comment]
已经解决了。。。子module中使用ButterKnife使用ButterKnife插件就可以了

**Comment by noterpopo** [comment]
> 已经解决了。。。子module中使用ButterKnife使用ButterKnife插件就可以了

解决了就好
